### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by hellocoldworld** [jucacrispim/pylint-mongoengine#10]
Hello! I am very interested in this project, but struggling to find documentation? There is some?
Also, there is a roadmap for future development? Or is this a "dead" project?

**Comment by jucacrispim** [comment]
Hi!
The project is not dead, but It has what I need, so I'm not implementing anything now, but one can send  ideas or PRs, they are very welcome.

About the docs the project has only its readme, this plugin doesn't have any options or anything, and it is really lacking some dev docs.

**Comment by hellocoldworld** [comment]
Thank you for your response.
