### ISSUE TITLE
Update to pylint-plugin-utils > 0.4

### ISSUE THREAD

**Issue by singingwolfboy** [jucacrispim/pylint-mongoengine#5]
It would be great if this plugin used `pylint-plugin-utils` at version 0.5 or higher, due to this bug: https://github.com/PyCQA/pylint-plugin-utils/issues/12

**Comment by jucacrispim** [comment]
Hi!
It's done. I've updated `pylint-plugin-utils` and uploaded pylint-mongoengine==0.2.3 to PyPI.

Thank you!

**Comment by singingwolfboy** [comment]
Thanks, @jucacrispim! I really appreciate it. 💖
